config/routes.rb
Rails.application.routes.draw do
  resources :employers do
    resources :checks
  end
  resources :sessions
  resources :users
  resources :checks


  resources :tax_years do
    resources :checks
    resources :employers
    get 'employer/forms' => 'employers#form'
    get 'check/no_form' => 'checks#no_form'

  end
  post '/sessions/new', to: "sessions#create"
  get '/auth/facebook/callback' => 'sessions#create'
  root 'welcome#home'
  get '/tax_years/:id/sorted' => 'tax_years#sorted', :as => 'tax_years_sorted'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tax_year.rb
class TaxYear < ApplicationRecord
  belongs_to :user
  has_many :checks
  has_many :employers, through: :checks
  validates :year, uniqueness: {scope: :user_id}

  def self.employer_gigs(tax_year, employer)
    tax_year.checks.select do |check|
      check.employer == employer
    end
  end

  



end

app/controllers/tax_years_controller.rb
class TaxYearsController < ApplicationController

  def show
    @tax_year = TaxYear.find_by(id: params[:id])
    if current_user == @tax_year.user
      session[:current_tax_year_id] = @tax_year.id
    else
      redirect_to new_session_path
    end
  end

  def sorted
    @tax_year = TaxYear.find_by(id: params[:id])
    if current_user == @tax_year.user
      session[:current_tax_year_id] = @tax_year.id
    else
      redirect_to new_session_path
    end
  end
end

app/helpers/tax_years_helper.rb
module TaxYearsHelper

  


end

app/views/tax_years/_table.html.erb
<% employer_collection.each do |employer| %>
  <div class= "text-left"><%= link_to employer.name, tax_year_employer_path(current_tax_year, employer) %></div>
  <div>
    <table >
      <thead>
        <th>Check Date</th><th>Name</th><th>Amount</th>
        <th>Mileage</th>
      </thead>
      <tbody id="table-<%=employer.id%>">
        <% employer.checks.by_year(current_tax_year).each do |check| %>
        <tr>
          <td><%= check.check_date.strftime("%m/%d/%Y") %></td>
          <td><%= link_to check.name, tax_year_check_path(check.tax_year, check), class: 'check', id: check.id, data_set: check.tax_year.id%></td>
          <td>$<%=check.amount%></td>
          <td><%=check.mileage%></td>
        </tr>
        <% end %>
        <tr id= "total-<%=employer.id%>">
          <td></td>
          <td>Total</td>
          <td>$<%= employer.checks.total_amount %></td>
          <td><%= employer.checks.total_mileage %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <br><br>
  <% end %>

app/views/tax_years/_table_with_employers.html.erb
  <table>
    <thead>
      <th>Check Date</th><th>Name</th><th>Employer Name</th><th>Amount</th>
      <th>Mileage</th>
    </thead>
    <tbody id='no-form-table'>
        <% no_form_checks.each do |check| %>
          <% if check.tax_year == @tax_year %>
            <tr>
              <td><%= check.check_date.strftime("%m/%d/%Y") %> </td>
              <td><%= link_to check.name, tax_year_check_path(check.tax_year, check), class: 'check', id: check.id %> </td>
              <td><%= link_to check.employer.name, employer_path(check.employer)%><%=" "%> </td>
              <td>$<%= check.amount %></td>
              <td><%= check.mileage %></td>
            </tr>
          <% end %>
      <% end %>
      <tr id='no-form-total'>
        <td></td>
        <td></td>
        <td>Total</td>
        <td>$<%= no_form_checks.sum(&:amount) %></td>
        <td><%= no_form_checks.sum(&:mileage) %></td>
      </tr>
    </tbody>
  </table>

app/views/tax_years/old_show.html.erb
<h1><%=@tax_year.user.username %> - <%=@tax_year.year%> Freelance Income</h1>
<%= link_to "Create a check", new_tax_year_check_path(tax_year_id: @tax_year.id), class: "newCheck" %><br>
<%= link_to "Sort By Employer", tax_years_sorted_path(@tax_year.id)%>
<%= content_tag :div, class: "id", data: {temp: @tax_year.id} do %>
<% end %>

<div class="row">
  <div class="col-md">
    <h2 class= "text-left">Income from Form 1099's</h2>
    <div>
      <%= render partial: 'table', locals: {employer_collection: @tax_year.employers.tax_form.uniq, current_tax_year: @tax_year} %>
    </div>
    <br><br>

    <h2 class= "text-left">Income without 1099's</h2>
    <%= render partial: 'table_with_employers', locals: {no_form_checks: @tax_year.checks.no_checks, current_tax_year: @tax_year} %><br>
  </div>
  <div class="col-md">

    <div class="newForm">

        <%= form_for Check.new, url: tax_year_checks_path(@tax_year) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %><br>
          <%= f.label 'Date on Check'%>
          <%= f.date_field :check_date%><br>
          <%= f.label :amount %>
          <%= f.number_field :amount, class: :text_field, step: :any %><br>
          <%= f.label 'Miles Driven (Round-Trip)' %>
          <%= f.number_field :mileage %><br>
          <%= f.label 'Select an Employer' %>
          <%= f.collection_select :employer_id, @tax_year.employers.uniq, :id, :name, include_blank: true %><br>
          <%= f.label 'Or Write the Name of a New One' %>
          <%= f.text_field :employer %><br>
          <%= f.label :description %>
          <%= f.text_area :description %><br>
          <%= f.submit id: "submit_button" %>
        <% end %>
    </div>

    <div id="checkResult">
      <h2 id="yourNew"></h2>
      <h4 id="checkName"></h4>
      <p id="checkDate"></p>
      <p id="checkAmount"></p>
      <p id="checkMileage"></p>
      <p id="checkEmployer"></p>
      <p id="checkDescription"></p>
      <p id="checkEditLink"></p>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
$(function() {
  $(".newCheck").click(function(event) {
    event.preventDefault()
    document.querySelector('#checkResult').style.display= "none"
    document.querySelector('.newForm').style.display= "inline"
    let id = $('.id').data('temp')
  })
})
</script>
<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      createAndDisplayCheck(event)
    })
  })
</script>
<a href=></a>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('.check').click(function(event) {
      document.querySelector('.newForm').style.display= "none"
      document.querySelector('#checkResult').style.display= "inline"
      let id = $('.id').data('temp')
      event.preventDefault()
      let answer= fetch(`/tax_years/${id}/checks/${event.target.id}.json`)
      .then(response => response.json())
      .then(json => {
        check = new Check(json)
        $('#checkName').text(`Name: ${check['name']}`)
        let date = new Date(check['check_date'])
        $('#checkDate').text(`Date: ${date.toDateString()}`)
        $('#checkAmount').text(`Amount: $${check['amount']}`)
        $('#checkMileage').text(`Mileage: ${check['mileage']}`)
        $('#checkEmployer').text(`Employer: ${check['employer']}`)
        $('#checkDescription').text(`Description: ${check['description']}`)
        let edit = document.querySelector('#checkEditLink')
        edit.innerHTML = `<a href="/checks/${check.id}/edit">Edit Check</a>`
      })
    })
  })
</script>

app/views/tax_years/show.html.erb
<h1><%=@tax_year.user.username %> - <%=@tax_year.year%> Freelance Income</h1>
<%= link_to "Create a check", new_tax_year_check_path(tax_year_id: @tax_year.id), class: "newCheck" %><br>
<%= content_tag :div, class: "id", data: {temp: @tax_year.id} do %>
<% end %>

<div class="row">
  <div class="col-md">

    <h2 class= "text-left">Income from Form 1099's</h2>
    <div id= "employers" class="text-left">

    </div>
    <h2 class= 'text-left'>Income without Form 1099's</h2>
    <div id="no_form_container" class="text-left">

    </div>
  </div>

  <div class="col-md">
    <div class="newForm">
        <%= form_for Check.new, url: tax_year_checks_path(@tax_year) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %><br>
          <%= f.label 'Date on Check'%>
          <%= f.date_field :check_date%><br>
          <%= f.label :amount %>
          <%= f.number_field :amount, class: :text_field, step: :any %><br>
          <%= f.label 'Miles Driven (Round-Trip)' %>
          <%= f.number_field :mileage %><br>
          <%= f.label 'Select an Employer' %>
          <%= f.collection_select :employer_id, @tax_year.employers.uniq, :id, :name, include_blank: true %><br>
          <%= f.label 'Or Write the Name of a New One' %>
          <%= f.text_field :employer %><br>
          <%= f.label :description %>
          <%= f.text_area :description %><br>
          <%= f.submit id: "submit_button" %>
        <% end %>
    </div>
    <div id="checkResult">
      <h2 id="yourNew"></h2>
      <h4 id="checkName"></h4>
      <p id="checkDate"></p>
      <p id="checkAmount"></p>
      <p id="checkMileage"></p>
      <p id="checkEmployer"></p>
      <p id="checkDescription"></p>
      <p id="checkEditLink"></p>
    </div>
    <div class="employerResult">
      <h2></h2>
    </div>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener('turbolinks:load', displayFormEmployers())
  document.addEventListener('turbolinks:load', displayNoFormChecks())
  </script>

<script type="text/javascript" charset="utf-8">
$(function() {
  $(".newCheck").click(function(event) {
    event.preventDefault()
    document.querySelector('#checkResult').style.display= "none"
    document.querySelector('.newForm').style.display= "inline"
  })
})
</script>
<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      createAndDisplayCheck(event)
    })
  })
</script>
<a href=></a>

app/views/tax_years/sorted.html.erb
<h1 data:"<%=@tax_year.id%>"><%=@tax_year.year%> Checks Sorted By Employers</h1>
<%= content_tag :div, class: "id", data: {temp: @tax_year.id} do %>
<% end %><br><br>
<div class="row">
  <div class="col-md">
    <button type="button" name="button" onclick="loadEmployers()">Show Employers</button><br>
    <button type="button" name="button"></button>

  <div id="employers" class='text-left'>

  </div>
</div>
</div>


<script type="text/javascript" charset="utf-8">
</script>