config/routes.rb
Rails.application.routes.draw do
  resources :employers do
    resources :checks
  end
  resources :sessions
  resources :users
  resources :checks


  resources :tax_years do
    resources :checks
    resources :employers
    get 'employer/forms' => 'employers#form'
    get 'check/no_form' => 'checks#no_form'

  end
  post '/sessions/new', to: "sessions#create"
  get '/auth/facebook/callback' => 'sessions#create'
  root 'welcome#home'
  get '/tax_years/:id/sorted' => 'tax_years#sorted', :as => 'tax_years_sorted'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employer.rb
class Employer < ApplicationRecord
  belongs_to :user
  has_many :checks
  scope :tax_form, -> { where(tax_form: true)}
  validates :name, presence: true

  def self.no_form
    where(tax_form: false)
  end

  def self.employer_checks(year)
    checks = []
    self.all.each {|employer| checks << employer.checks.by_year(year)}
    checks
  end

  def self.no_form_total_amount(current_tax_year)
    self.no_form.employer_checks.by_year(current_tax_year).total_amount
  end

  def self.no_form_total_mileage
    self.map{|employer| employer.mileage}.by_year(current_tax_year).total_mileage
  end

  def self.no_form_check_amounts
    total = 0
    map {|employer| employer.checks}.uniq
  end


end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  def index
    @tax_year = TaxYear.find_by(id: params[:tax_year_id])
    @employers = @tax_year.employers.uniq
    respond_to do |format|
      format.html
      format.json {render json: @employers, each_serializer: EmployerSerializer, status: 201}
    end
  end

  def form
    @tax_year = TaxYear.find_by(id: params[:tax_year_id])
    @employers = @tax_year.employers.tax_form.uniq
    respond_to do |format|
      format.html
      format.json {render json: @employers, each_serializer: EmployerSerializer, status: 201}
    end
  end
  
  def show
    @employer = Employer.find_by(id: params[:id])
    if !current_user = @employer.user
      redirect_to new_session_path
    end
  end

  def edit
    @employer = Employer.find_by(id: params[:id])
  end

  def update
    @employer = Employer.find_by(id: params[:id])
    @employer.update(update_params)
    if @employer.save
      tax_year = TaxYear.find_by(id: session[:current_tax_year_id])
      redirect_to tax_year_path(tax_year)
    else
      render :edit
    end
  end

  def destroy
    @employer = Employer.find_by(id: params[:id])
    @employer.destroy
    redirect_to tax_year_path(id: session[:current_tax_year_id])
  end

  private

  def update_params
    params.require(:employer).permit(:name, :tax_form)
  end
end

app/helpers/employers_helper.rb
module EmployersHelper

  def lucrative?(employer)
    total = 0
    employer.checks.each do |check|
      total += check.amount
    end
    if total > 600
      true
    else
      false
    end
  end
end

app/views/employers/_table_with_tax_years.html.erb
<% tax_years.each do |tax_year| %>
<h4><%= link_to tax_year.year, tax_year_path(tax_year) %></h4>
<table>
  <thead>
    <th>Check Date</th><th>Name</th><th>Amount</th>
    <th>Mileage</th>
  </thead>
    <tbody>
      <% tax_year.checks.each do |check| %>
        <% if check.employer == employer %>
          <tr>
            <td><%= check.check_date.strftime("%m/%d/%Y") %></td>
            <td><%=check.name%></td>
            <td>$<%=check.amount%></td>
            <td><%=check.mileage%></td>
          </tr>
        <% end %>
      <% end %>
      <tr>
        <td></td>
        <td>Total</td>
        <td>$<%= tax_year.checks.by_employer(employer).sum(&:amount) %></td>
        <td><%= tax_year.checks.by_employer(employer).sum(&:mileage) %></td>
      </tr>
    </tbody>
</table>
<% end %>

app/views/employers/edit.html.erb
<%= form_for @employer do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label 'Expecting a Form 1099 from this employer?' %>
  <%= f.check_box :tax_form %><br>
  <%= f.submit %>
<% end %>

app/views/employers/show.html.erb
<h1><%= @employer.name %></h1>
<%= link_to 'Edit Employer Info', edit_employer_path(@employer) %>




<%# <%= render partial: 'table_with_tax_years', locals: {tax_years: @employer.tax_years.uniq, employer: @employer} %> 
<br><br>

<%= button_to "Delete Employer", employer_path(:id => @employer.id), :method => :delete %>