config/routes.rb
Rails.application.routes.draw do
  resources :employers do
    resources :checks
  end
  resources :sessions
  resources :users
  resources :checks


  resources :tax_years do
    resources :checks
    resources :employers
    get 'employer/forms' => 'employers#form'
    get 'check/no_form' => 'checks#no_form'

  end
  post '/sessions/new', to: "sessions#create"
  get '/auth/facebook/callback' => 'sessions#create'
  root 'welcome#home'
  get '/tax_years/:id/sorted' => 'tax_years#sorted', :as => 'tax_years_sorted'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
  belongs_to :tax_year
  belongs_to :employer
  validates :check_date, presence: true
  validates :name, presence: true
  validates :amount, presence: true
  validates :mileage, presence: true

  def has_1099
    self.employer.tax_form
  end

  def self.by_year(year)
    where(tax_year: year)
  end

  def self.by_employer(employer)
    where(employer: employer)
  end

  def self.total_amount
    sum(&:amount)
  end

  def self.other_total_amount
    amounts = self.map{|check| check.amount}
    amounts.sum
  end

  def self.total_mileage
    sum(&:mileage)
  end

  def self.no_checks
    self.select{|check| check.employer.tax_form === false }
  end

end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def index
    employer = Employer.find_by(id: params[:employer_id])
    @checks = employer.checks
    respond_to do |format|
      format.html
      format.json {render json: @checks, each_serializer: CheckSerializer, status: 201}
    end
  end

  def no_form
    tax_year = TaxYear.find_by(id: params[:tax_year_id])
    @checks = tax_year.checks.no_checks
    respond_to do |format|
      format.html
      format.json {render json: @checks, each_serializer: CheckSerializer, status: 201}
    end
  end

  def show
    @check = Check.find_by(id: params[:id].to_i)
    respond_to do |format|
      format.html
      format.json {render json: @check, status: 201}
    end
  end

  def new
    @check = Check.new
    @check.tax_year = TaxYear.find_by(id: session[:current_tax_year_id])
  end

  def create
    @check = Check.new(check_params)
    @check.tax_year = TaxYear.find_by(id: params[:tax_year_id])
    @check.user = User.find_by(id: session[:user_id])
    if !params[:check][:employer].empty?
      @check.employer = Employer.find_or_create_by(name: params[:check][:employer], user: User.find(session[:user_id]))
    end
    if @check.save
      respond_to do |format|
        format.html
        format.json {render json: @check, status: 201}
      end
    else
      render :new
    end
  end

  def edit
    @check = Check.find_by(id: params[:id])
  end

  def update
    @check = Check.find_by(id: params[:id])
    if @check.update(check_params)
      redirect_to tax_year_check_path(@check)
    else
      render :edit
    end
  end

  def destroy
    @check = Check.find_by(id: params[:id])
    @tax_year = @check.tax_year
    @check.destroy
    redirect_to tax_year_path(@tax_year)
  end


  private

  def check_params
    params.require(:check).permit(:name, :amount, :mileage, :employer_id, :check_date, :description, employer_attributes: [:name])
  end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_check_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label 'Date on Check'%>
<%= f.date_field :check_date%><br>
<%= f.label :amount %>
<%= f.number_field :amount, class: :text_field, step: :any %><br>
<%= f.label 'Miles Driven (Round-Trip)' %>
<%= f.number_field :mileage %><br>
<%= f.label 'Select an Employer' %>
<%= f.collection_select :employer_id, @check.tax_year.employers.uniq, :id, :name, include_blank: true %><br>
<% if !@check.employer %>
<%= f.fields_for :employer do |em| %>
  <%= em.label 'Or Name of a New Employer' %>
  <%= em.text_field :name %><br>
<% end %>
<%= f.submit %>

app/views/checks/edit.html.erb
<%= render partial: 'users/errors', locals: {object: @check}  %>
<%= content_tag :div, class: "tyid", data: {temp: @check.tax_year.id} do %>
<% end %>
<%= content_tag :div, class: "id", data: {temp: @check.id} do %>
<% end %>



<%= form_for(@check, url: tax_year_check_path(@check)) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label 'Date on Check'%>
  <%= f.date_field :check_date%><br>
  <%= f.label :amount %>
  <%= f.number_field :amount, class: :text_field, step: :any %><br>
  <%= f.label 'Miles Driven (Round-Trip)' %>
  <%= f.number_field :mileage %><br>
  <%= f.label 'Select an Employer' %>
  <%= f.collection_select :employer_id, @check.tax_year.employers.uniq, :id, :name, include_blank: true %><br>
  <% if !@check.employer %>
    <%= f.fields_for :employer do |em| %>
      <%= em.label 'Or Name of a New Employer' %>
      <%= em.text_field :name %><br>
    <% end %>
  <% end %>
  <%= f.label :description %>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<% end %>
<br><br>

<%= button_to "Delete Check", tax_year_check_path(@check.tax_year, @check), tax_year_id: @check.tax_year, :method => :delete %>

app/views/checks/new.html.erb
<% if @check.id %>
<% else %>

  <%= render partial: 'users/errors', locals: {object: @check} %>
  <%= content_tag :div, class: "id", data: {temp: @check.tax_year.id} do %>
  <% end %>


  <%= form_for @check, url: tax_year_checks_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label 'Date on Check'%>
    <%= f.date_field :check_date%><br>
    <%= f.label :amount %>
    <%= f.number_field :amount, class: :text_field, step: :any %><br>
    <%= f.label 'Miles Driven (Round-Trip)' %>
    <%= f.number_field :mileage %><br>
    <%= f.label 'Select an Employer' %>
    <%= f.collection_select :employer_id, @check.tax_year.employers.uniq, :id, :name, include_blank: true %><br>
    <% if !@check.employer %>
      <%= f.label 'Or Write the Name of a New One' %>
      <%= f.text_field :employer %><br>
    <% end %>
    <%= f.label :description %>
    <%= f.text_area :description %><br>
    <%= f.submit id: "submit_button" %>
  <% end %>
<% end %>


<div id="checkResult">
  <h2 id="yourNew"></h2>
  <h4 id="checkName"></h4>
  <p id="checkDate"></p>
  <p id="checkAmount"></p>
  <p id="checkMileage"></p>
  <p id="checkEmployer"></p>
  <p id="checkDescription"></p>
</div>


<script type="text/javascript" charset="utf-8">
  $(function () {
    let id = $('.id').data('temp')
    $('form').submit(function(event) {
      event.preventDefault();
      let newForm = document.querySelector('#new_check')
      newForm.style.display = 'none'
      var values = $(this).serialize()
      var posting = $.post(`/tax_years/${id}/checks`, values)
      posting.done(function(data) {
        var check = data
        $('#yourNew').text('Your New Check:')
        $('#checkName').text(`Name: ${check['name']}`)
        let date = new Date(check['check_date'])
        $('#checkDate').text(`Date: ${date.toDateString()}`)
        $('#checkAmount').text(`Amount: ${check['amount']}`)
        $('#checkMileage').text(`Mileage: ${check['mileage']}`)
        $('#checkEmployer').text(`Employer: ${check['employer']['name']}`)
        $('#checkDescription').text(`Description: ${check['description']}`)
      })
    })
  })
</script>

app/views/checks/show.html.erb
<h1 id="checkName"><%= @check.name %></h1> <br><br>

<h3 id="checkDescription">Description:</h3>
<p><%=@check.description %></p><br>

<%=link_to 'Edit Check', edit_tax_year_check_path(@check)%><br>

<button type="button" name="next_button" class= "next" data-id= "<%=@check.id%>" data-ty= "<%=@check.tax_year.id%>">Next Check</button>


<script type="text/javascript">
  $(function () {
  $("button.next").on("click", function(event) {
    event.preventDefault()
    var nextId = parseInt($(".next").attr("data-id")) + 1;
    tyId = parseInt($(".next").attr("data-ty"))
    var getting = $.get(`/tax_years/${nextId}/checks/${tyId}`)
    getting.done(function(data) {
      debugger
      $(".checkName").text(data["name"]);
      $(".checkDescription").text(data["description"]);
      // re-set the id to current on the link
      $("button.next").attr("data-id", data["id"]);
    });
  });
});
</script>